"""made some column unique

Revision ID: 02981ae6b7e8
Revises: 4bad536f7934
Create Date: 2023-10-16 23:05:26.583934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02981ae6b7e8'
down_revision: Union[str, None] = '4bad536f7934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customers', ['phone_no'])
    op.create_unique_constraint(None, 'customers', ['email'])
    op.create_unique_constraint(None, 'vendors', ['phone_no'])
    op.create_unique_constraint(None, 'vendors', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    # ### end Alembic commands ###
