"""added password column

Revision ID: 21f6eefe0151
Revises: 874e095dd722
Create Date: 2023-10-24 23:57:09.602818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f6eefe0151'
down_revision: Union[str, None] = '874e095dd722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('password', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'vendors', ['password'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_column('vendors', 'password')
    # ### end Alembic commands ###
