"""added a python coulumn

Revision ID: 2f961802d089
Revises: 77959f546505
Create Date: 2023-10-23 12:02:24.860711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f961802d089'
down_revision: Union[str, None] = '77959f546505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'password')
    # ### end Alembic commands ###
