"""added password(unique)

Revision ID: 45e4bfd65f21
Revises: 21f6eefe0151
Create Date: 2023-10-25 00:49:32.756372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45e4bfd65f21'
down_revision: Union[str, None] = '21f6eefe0151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'password',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
