"""made vendor_id unique

Revision ID: 77959f546505
Revises: fd4e49313144
Create Date: 2023-10-23 00:04:27.818210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77959f546505'
down_revision: Union[str, None] = 'fd4e49313144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'restaurants', ['vendor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='unique')
    # ### end Alembic commands ###
