"""deleted password column

Revision ID: 874e095dd722
Revises: 74c6048447b2
Create Date: 2023-10-24 23:55:46.934426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '874e095dd722'
down_revision: Union[str, None] = '74c6048447b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('password', 'vendors', ['password'], unique=False)
    # ### end Alembic commands ###
