"""empty message

Revision ID: 3b3174f311ff
Revises: 2993fdf09e44
Create Date: 2024-03-22 01:36:46.482195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3174f311ff'
down_revision: Union[str, None] = '2993fdf09e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('hashed_password', sa.String(length=256), nullable=False))
    op.drop_column('vendors', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('vendors', 'hashed_password')
    # ### end Alembic commands ###
