"""added a column on customer table

Revision ID: 7c2b205603be
Revises: f9b26c46d16b
Create Date: 2024-03-25 16:04:50.774079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2b205603be'
down_revision: Union[str, None] = 'f9b26c46d16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone_no_verify_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'phone_no_verify_status')
    # ### end Alembic commands ###
