"""added reset token

Revision ID: f9b26c46d16b
Revises: 3b3174f311ff
Create Date: 2024-03-22 23:40:16.132325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b26c46d16b'
down_revision: Union[str, None] = '3b3174f311ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('reset_token', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'reset_token')
    # ### end Alembic commands ###
